### ISSUE TITLE
ROS2 port yocs_cmd_vel mux - TODO

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#406]
Migrate from [yujin_ocs/yocs_cmd_vel_mux](https://github.com/yujinrobot/yujin_ocs/tree/devel/yocs_cmd_vel_mux) since that repository is not likely to survive the transition to ROS2.

* [ ] Create a standalone package (not in kobuki, since it's more general)
* [ ] Upgrade build infra
* [ ] Working Code
* [ ] Revamped Launchers and Tests
