### ISSUE TITLE
ROS2 port yocs_velocity_smoother - TODO

### ISSUE THREAD

**Issue by clalancette** [yujinrobot/kobuki#407]
#405 is a first port of the velocity_smoother to ROS 2.  It ports the main bulk of the code, but there are several things left to do:

* [x] Create example parameter files for ROS 2
* [x] Port the launch files to ROS 2
* [x] Create an example composable launch file for ROS 2
* [ ] Port the tests to ROS 2
* [ ] Test the package in a complete system

**Comment by corot** [comment]
Should we delete devel branch on this repo, so nobody tries to use it instead of https://github.com/kobuki-base?
